---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-app-pvc
  labels:
    appname: busybox-app
    placement: busybox-app-placement-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
